name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    name: Basic CI Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Placeholder Test
      run: |
        echo "Running placeholder test"
        echo "Test passed successfully!"
        exit 0
        
    - name: Placeholder Build
      run: |
        echo "Running placeholder build"
        echo "Build completed successfully!"
        exit 0
        
    - name: Placeholder Lint
      run: |
        echo "Running placeholder lint check"
        echo "Lint check passed!"
        exit 0

  notify:
    name: Notification
    needs: build
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Send Status
      run: |
        echo "Pipeline completed"
        echo "Status: Success"